### PR TITLE
Pykcs11 integration

### PR DESCRIPTION
**Pull request by DanielAviv**
Rewrote the PKCS11 classic test in Python

### CODE REVIEW

**Comment by fmontoto** [comment]
- I would prefer the imports at the top  of the file, as it's easier to see dependencies of the code. Do you have a good reason to place them inside functions?
- Add the test to system_test suite and run it by default in travis.

**Comment by franchoco** [comment]
It would be nice have command line options for the TCHSM_CONFIG and PYKCS11LIB environment variables. The script may set the environment variables at startup.

**Comment by DanielAviv** [comment]
@fmontoto 
1) Not really, I placed it there so it imports only when doing the verification, if you don't like it I can change it to the header again. ;)
2) I'm planning to do this in a separate branch, when I edit the system_test suite to add the features we discussed earlier.

@franchoco 
1) Sure, no prob :)

**Comment by fmontoto** [comment]
1) Move them please.
2) Ok
3) please change the name of the function verify, as it it's signing and verifying. _sign_and_verify_ (?)

**Comment by DanielAviv** [comment]
@fmontoto Ready for revision

**Comment by DanielAviv** [comment]
@fmontoto Wait no, don't merge yet!!

**Comment by DanielAviv** [comment]
@fmontoto Now, its absolutely and without a doubt, and with git as my witness, ready for revision

**Pull request merged**
